# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept.
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

config.set('content.cookies.accept', 'all', 'devtools://*')

#Content headers
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:131.0) Gecko/20100101 Firefox/131.0', 'https://accounts.google.com/*')

# Load images automatically in web pages.
config.set('content.images', True, 'chrome-devtools://*')

config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

config.set('content.javascript.enabled', True, 'devtools://*')

config.set('content.javascript.enabled', True, 'chrome://*/*')

config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow locally loaded documents to access remote URLs.
config.set('content.local_content_can_access_remote_urls', True, 'file:///home/user/.local/share/qutebrowser/userscripts/*')

# Allow locally loaded documents to access other local URLs.
config.set('content.local_content_can_access_file_urls', False, 'file:///home/user/.local/share/qutebrowser/userscripts/*')

# Number of commands to save in the command history. 0: no history / -1:
c.completion.cmd_history_max_items = 0

# Search engines which can be used via the address bar.  Maps a search
c.url.searchengines = {'DEFAULT': 'https://google.com/search?hl=en&q={}'}

#Set start page
c.url.start_pages = ['about:blank']

# Render all web contents using a dark theme.
c.colors.webpage.darkmode.enabled = True

# Bindings for normal mode
config.bind('H', 'back')
config.bind('backspace', 'back')
config.unbind('d')
config.bind('q', 'tab-close')
