tap "homebrew/bundle"
brew "gmic"
brew "gnupg"
brew "imagemagick"
brew "mas"
brew "neovim"
brew "zenity"
cask "alacritty"
cask "bettertouchtool"
cask "blender"
cask "calibre"
cask "commandpost"
cask "downie"
cask "find-any-file"
cask "firefox"
cask "handbrake"
cask "iina"
cask "jellyfin"
cask "pomatez"
cask "sensiblesidebuttons"
cask "spaceid"
mas "Hidden Bar", id: 1452453066
mas "Little Snitch Mini", id: 1629008763
mas "Pixelmator Pro", id: 1289583905
