#turn laptop monitor off when lid is closed
#exec_always kanshictl
#bindswitch --reload --locked lid:off exec kanshictl switch lid-opened
#bindswitch --reload --locked lid:on exec kanshictl switch lid-closed
#exec_always "systemctl--user restart kanshi.service"
