# bindings
$bindsym $mod+return exec $term
# $bindsym super+space exec $menu
# $bindsym $mod+alt+1 exec /home/user/.config/sway/scripts/nvim.sh
# $bindsym $mod+alt+2 exec celluloid
$bindsym super+q kill
$bindsym super+Shift+q mode $mode_shutdown
